services:
  - type: web
    name: cegquiz-dashboard
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python dashboard_app.py
    envVars:
      - key: DASHBOARD_SECRET
        sync: false
  - type: worker
    name: cegquiz-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
